environment:
  pds3_holdings_root: /mnt/ganymede/PDS/holdings
  results_root: /data/nav-offset-results

general:
  log_level_nav_stars: DEBUG
  log_level_model_stars: DEBUG
  log_level_annotate: ERROR
