environment:
  pds3_holdings_root: /mnt/ganymede/PDS/holdings
  results_root: /data/nav-offset-results

general:
  nav_stars_log_level: DEBUG
  model_stars_log_level: INFO
  annotate_log_level: ERROR
