##############################################
# PDS4 BUNDLE DEFAULT CONFIGURATION SETTINGS #
##############################################

pds4:
  coiss_saturn:
    template_dir: cassini_iss_saturn_1.0
    bundle_name: cassini_iss_saturn_backplanes_rsfrench2027
  # Add other datasets as needed
  # gossi:
  #   template_dir: galileo_ssi_jupiter_1.0
  #   bundle_name: galileo_ssi_jupiter_backplanes_rsfrench2027
  # nhlorri:
  #   template_dir: newhorizons_lorri_pluto_1.0
  #   bundle_name: newhorizons_lorri_pluto_backplanes_rsfrench2027
  # vgiss:
  #   template_dir: voyager_iss_saturn_1.0
  #   bundle_name: voyager_iss_saturn_backplanes_rsfrench2027
