cassini_iss:
  nac:
    extfov_margin_vu:
      256: [13, 25]
      512: [25, 50]
      1024: [50, 100]
    star_psf_sigma: 0.54
    star_psf_sizes:
      7: [11, 11]
      8: [9, 9]
      100: [7, 7]
  wac:
    extfov_margin_vu:
      256: [5, 10]
      512: [5, 10]
      1024: [5, 10]
    star_psf_sigma: 0.77
    star_psf_sizes:
      7: [11, 11]
      8: [9, 9]
      100: [7, 7]
