name: Run Tests
run-name: Run Tests triggered by ${{ github.ref_type }} ${{ github.ref_name }} or ${{ github.triggering_actor }}

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: "21 11 * * 0"

jobs:
  lint:
    name: Lint rms-nav
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install -e ".[dev]"

      - name: Ruff (lint)
        run: |
          ruff check src tests

      - name: Mypy
        run: |
          mypy src tests

      - name: Sphinx
        run: |
          sphinx-build -b html docs docs/_build

      - name: PyMarkdown
        run: |
          pymarkdown scan docs/ .cursor/ README.md CONTRIBUTING.md
  
  test:
    name: Test rms-nav
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13']
      fail-fast: false
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -e ".[dev]"

      - name: Test with coverage
        run: |
          export PDS3_HOLDINGS_DIR=https://pds-rings.seti.org/holdings
          export PDS4_HOLDINGS_DIR=https://pds-rings.seti.org/pds4
          export OOPS_RESOURCES=https://storage.googleapis.com/rms-node-oops-resources
          export UCAC4_PATH=https://storage.googleapis.com/rms-node-star-catalogs/UCAC4
          export YBSC_PATH=https://storage.googleapis.com/rms-node-star-catalogs/YBSC
          python -m pytest --cov -n auto

      - name: Print coverage report
        run: |
          coverage report -m

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v5
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
